language: cpp
sudo: required
dist: trusty
git:
  depth: 9999999
notifications:
  irc: chat.freenode.net#zoneminder-dev
branches:
  except:
  - modern
cache: ccache
addons:
  ssh_known_hosts: zmrepo.zoneminder.com
  apt:
    sources:
    - sourceline: ppa:iconnor/zoneminder
    - key_url: http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4D0BF748776FFB04
    packages:
    - gdebi
    - yum-utils
    - patch
    - git
    - curl
    - sshfs
    - sed
    - binfmt-support
    - qemu
    - qemu-user-static
    - dnsutils
    - traceroute
install:
  - update-binfmts --enable qemu-arm

env:
  global:
  - SMPFLAGS=-j4
  matrix:
  - OS=el DIST=7
  - OS=fedora DIST=27 DOCKER_REPO=knnniggett/packpack
  - OS=fedora DIST=28 DOCKER_REPO=knnniggett/packpack
  - OS=fedora DIST=29 DOCKER_REPO=knnniggett/packpack
  - OS=ubuntu DIST=trusty
  - OS=ubuntu DIST=xenial
  - OS=ubuntu DIST=trusty ARCH=i386
  - OS=ubuntu DIST=xenial ARCH=i386
  - OS=raspbian DIST=stretch ARCH=armhf DOCKER_REPO=knnniggett/packpack

compiler:
- gcc
services:
- mysql
- docker
script:
- utils/packpack/startpackpack.sh

before_deploy:
- openssl aes-256-cbc -K $encrypted_62a62750aa73_key -iv $encrypted_62a62750aa73_iv -in ./utils/packpack/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: utils/packpack/rsync_xfer.sh
  on:
    branch: master

