# Site settings
name: ZoneMinder
title: Linux video camera security and surveillance solution.
email: your-email@domain.com
description: "ZoneMinder is a free, open source CCTV Linux application which supports monitoring, alerting and recording of IP, USB and analog cameras. Use it with just about any camera to monitor your home, business, crib, or anything else."
baseurl: ""
url: "http://zoneminder.com"

# Build settings
markdown: kramdown
permalinks: pretty
