name: CI CentOS 7

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        crypto_backend: [ gnutls, openssl ]
        jwt_backend: [ libjwt, jwt_cpp ]
        exclude:
          - crypto_backend: gnutls
            jwt_backend: jwt_cpp
          - crypto_backend: gnutls
            jwt_backend: libjwt
    runs-on: ubuntu-latest
    container: centos:7

    steps:
      - name: Enable RPMFusion and EPEL
        run: yum -y install https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - name: Install git
        run: yum -y install https://repo.ius.io/ius-release-el7.rpm && yum -y install git224
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: yum -y update && yum -y install make cmake3 gcc-c++ mariadb-devel ffmpeg-devel libcurl-devel vlc-devel libvncserver-devel libjpeg-turbo-devel "perl(Date::Manip)" "perl(DBD::mysql)" "perl(ExtUtils::MakeMaker)" "perl(Sys::Mmap)" "perl(Sys::Syslog)" "perl(LWP::UserAgent)" polkit-devel libjwt-devel fmt-devel
      - name: Prepare
        run: mkdir build
      - name: Configure
        run: cd build && cmake3 --version && cmake3 .. -DBUILD_MAN=0 -DENABLE_WERROR=1 -DZM_CRYPTO_BACKEND=${{ matrix.crypto_backend }} -DZM_JWT_BACKEND=${{ matrix.jwt_backend }}
      - name: Build
        run: cd build && make -j3 | grep --line-buffered -Ev '^(cp lib\/|Installing.+\.pm)' && (exit ${PIPESTATUS[0]})
